### ISSUE TITLE
Add background image proxy

### ISSUE THREAD

**Issue by v0l** [GoomiiV2/NyaaSync#14]
Use a call to the nyaasync server instead of linking directly to the image and reveling the url to all clients and causing ssl error when non https image link.

![sslerror](https://void.cat/2b0eb1fdbaed3037389e328f272a1f6660c877fa)

**Comment by GoomiiV2** [comment]
I have been trying to avoid hosting well, pretty much anything, less hassle and Imgur for example, does it much better than I could.
Atm for known image hosts it will convert any http:// to https://.

It is less user friendly unfortunately.

**Comment by v0l** [comment]
Maybe

**Comment by v0l** [comment]
Well if you had very long cache expire times there wouldn't be really any load added to the site.
