### ISSUE TITLE
Make video load at correct position when joining. 

### ISSUE THREAD

**Issue by v0l** [GoomiiV2/NyaaSync#15]
```
this.player.loadVideoById({
    videoId: cvid.YoutubeVideoCode,
    startSeconds: data.FirstSongStartTime
});
```

Example code from [HAL](http://hal.xn--sve.com/main.js)

**Comment by GoomiiV2** [comment]
It should already do this.
Pages loads > Player loads > Waits about 2 seconds > Gets current player state (including time)

I did it that way as some browsers (I think it was Chrome?) wouldn't play properly on all the video providers.

**Comment by v0l** [comment]
I think it might be something to do with the socket not being connected yet?

`Uncaught TypeError: Cannot read property 'emit' of undefined`
`PRIVATE.roomSock.emit("getSync", null);`
